### ISSUE TITLE
Splitting up installation and infrastructure part

### ISSUE THREAD

**Issue by vanhuto** [osisoft/OSI-Samples-PI-System#39]
We have installed the OSI PI System without problem with the scripts provided in these samples. But now it's only possible to run the full script with the installation/configuration of the infrastructure included. Is it maybe possible to split up the project in 2 parts? So it's possible to skip the infrastructure part because a lot of people are maintaining them by themselves with another tool. This will make it easy for people to spin up quickly a development setup that can integrate with tools like TrendMiner for example.

**Comment by derekendres** [comment]
Hi currently we are using Feedback.osisoft.com to track issues in GitHub.  I moved this request to here: https://feedback.osisoft.com/forums/922279-osisoft-github/suggestions/39768628-split-up-installation-and-infrastructure-of-deploy
